// <auto-generated />
using System;
using ERP_Ferramenteiro.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ERP_Ferramenteiro.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528002649_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ERP_Ferramenteiro.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("text");

                    b.Property<string>("NomeRazaoSocial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Documento")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ERP_Ferramenteiro.Domain.Entities.Faturamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LocacaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetodoPagamento")
                        .HasColumnType("text");

                    b.Property<string>("StatusPagamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorFaturado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LocacaoId")
                        .IsUnique();

                    b.ToTable("Faturamentos");
                });

            modelBuilder.Entity("ERP_Ferramenteiro.Domain.Entities.Ferramenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatrimonioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoTamanho")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorDia")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("ValorHora")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorMes")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorSemana")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PatrimonioId")
                        .IsUnique();

                    b.ToTable("Ferramentas");
                });

            modelBuilder.Entity("ERP_Ferramenteiro.Domain.Entities.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("ERP_Ferramenteiro.Domain.Entities.Locacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataDevolucaoReal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataFimPrevista")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("Locacoes");
                });

            modelBuilder.Entity("ERP_Ferramenteiro.Domain.Entities.LocacaoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FerramentaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocacaoId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuantidadePeriodo")
                        .HasColumnType("integer");

                    b.Property<string>("TipoCobranca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorUnitarioAplicado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FerramentaId");

                    b.HasIndex("LocacaoId");

                    b.ToTable("LocacaoItens");
                });

            modelBuilder.Entity("ERP_Ferramenteiro.Domain.Entities.Faturamento", b =>
                {
                    b.HasOne("ERP_Ferramenteiro.Domain.Entities.Locacao", "Locacao")
                        .WithOne("Faturamento")
                        .HasForeignKey("ERP_Ferramenteiro.Domain.Entities.Faturamento", "LocacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Locacao");
                });

            modelBuilder.Entity("ERP_Ferramenteiro.Domain.Entities.Locacao", b =>
                {
                    b.HasOne("ERP_Ferramenteiro.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP_Ferramenteiro.Domain.Entities.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("ERP_Ferramenteiro.Domain.Entities.LocacaoItem", b =>
                {
                    b.HasOne("ERP_Ferramenteiro.Domain.Entities.Ferramenta", "Ferramenta")
                        .WithMany()
                        .HasForeignKey("FerramentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP_Ferramenteiro.Domain.Entities.Locacao", "Locacao")
                        .WithMany("Itens")
                        .HasForeignKey("LocacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ferramenta");

                    b.Navigation("Locacao");
                });

            modelBuilder.Entity("ERP_Ferramenteiro.Domain.Entities.Locacao", b =>
                {
                    b.Navigation("Faturamento")
                        .IsRequired();

                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
